### ISSUE TITLE
[Question] localhost:8080 direct to tomcat startpage

### ISSUE THREAD

**Issue by pixx1** [deegree/deegree3-docker#2]
Hello!
I heard about you at the FOSSGIS 2020 and want to try out deegree.

I simply run
`docker pull deegree/deegree3-docker:latest`
and
`docker run --name deegree -p 8080:8080 deegree/deegree3-docker`

but when I go to localhost:8080 I just see the tomcat startpage. 
Do I have to do something else to run deegree?

Thanks and greetings!
pix_1

**Comment by copierrj** [comment]
The docker command is you use is totally fine. You just have to go to http://localhost:8080/deegree-webservices/ instead.

**Comment by pixx1** [comment]
That was to easy.... thanks :)
