### ISSUE TITLE
readme on dockerhub needs update 

### ISSUE THREAD

**Issue by pvgenuchten** [deegree/deegree3-docker#5]
the information at https://hub.docker.com/r/deegree/deegree3-docker does not match https://github.com/deegree/deegree3-docker/blob/master/README.md, a reference is made to `docker exec -w /opt/deegree-tools-config/bin deegree ./d3config -help` which does not exist on latest docker image

**Comment by tfr42** [comment]
The mirror on docker hub is out of sync with the mail repo here on github, see #https://github.com/deegree/deegree3/issues/1172 for more info.
Updated the readme on docker hub manually.

**Comment by pvgenuchten** [comment]
Thank you @tfr42
